FROM python:3.12-slim

WORKDIR /app

LABEL maintainer="yourname@example.com" \
      version="1.0" \
      description="This is a Python API application using FastAPI and Uvicorn." \
      org.opencontainers.image.source="https://github.com/aleksander124/python-todo-app" \
      org.opencontainers.image.licenses="MIT"

COPY . .

# Set environment variables
ENV DB_USER=default_user \
    DB_PASSWORD=default_password \
    DB_NAME=default_db \
    DB_HOST=localhost \
    DB_PORT=5432

RUN echo "DB_USER=${DB_USER}" >> /app/app/.env \
    && echo "DB_PASSWORD=${DB_PASSWORD}" >> /app/app/.env \
    && echo "DB_NAME=${DB_NAME}" >> /app/app/.env \
    && echo "DB_HOST=${DB_HOST}" >> /app/app/.env \
    && echo "DB_PORT=${DB_PORT}" >> /app/app/.env \
    && { unset DB_USER; unset DB_PASSWORD; unset DB_NAME; unset DB_HOST; unset DB_PORT; }

RUN pip install --no-cache-dir -r requirements.txt

RUN chgrp -R 0 /app && \
    chmod -R g=u /app

USER 1001

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]